# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ChartsDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
	pod 'Charts', '4.0.2'
  # Pods for ChartsDemo

end
